#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    seoanalyse-web-80-http:
      entrypoints:
        - http-80
      rule: HostRegexp(`^seoanalyse\.ddev\.site$`)
      
      service: "seoanalyse-web-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "seoanalyse-redirectHttps"
    seoanalyse-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^seoanalyse\.ddev\.site$`)
      
      service: "seoanalyse-web-8025"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "seoanalyse-redirectHttps"
    
    
    
    seoanalyse-web-80-https:
      entrypoints:
        - http-443
      rule: HostRegexp(`^seoanalyse\.ddev\.site$`)
      
      service: "seoanalyse-web-80"
      ruleSyntax: v3
      
      tls: true
      
    seoanalyse-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^seoanalyse\.ddev\.site$`)
      
      service: "seoanalyse-web-8025"
      ruleSyntax: v3
      
      tls: true
      
    

  middlewares:
    seoanalyse-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    seoanalyse-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-seoanalyse-web:80
        
    seoanalyse-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-seoanalyse-web:8025
        
    
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/seoanalyse.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/seoanalyse.key