name: seoanalyse
type: php
docroot: visualizations
php_version: "8.2"
webserver_type: nginx-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
  type: postgres
  version: "14"
use_dns_when_possible: true
composer_version: "2"
corepack_enable: false
web_environment:
  - REDIS_HOST=redis
  - REDIS_PORT=6379
services:
  redis:
    type: redis:6
hooks:
  post-start:
    - exec: |
        sudo apt-get update && \
        sudo apt-get install -y php8.2-redis && \
        phpenmod redis
